### ISSUE TITLE
Circles to bboxes conversion process doesn't seem right

### ISSUE THREAD

**Issue by Wala-Touati** [Octomiro/octopipes#19]
The process `circles_to_bboxes` defined in `octopipes.process` doesn't convert to a conventional bbox format; it converts to `[X_min, Y_max, X_max, Y_min]` i assume that the intended format is `[X_min, Y_min, X_max, Y_max]` if so the function should change to this instead:
```Python
def circles_to_bboxes(circles) -> list:
    return [(int(x - r), int(y - r), int(x + r), int(y + r)) for x, y, r in circles]
```

**Comment by Wala-Touati** [comment]
I m also not sure where to handle this overflow nor why is it occurring
```Python
RuntimeWarning: overflow encountered in scalar subtract return [(int(x - r), int(y + r), int(x + r), int(y - r))
```

**Comment by thamerkhamassi** [comment]
This would probably solve the error
```Python
def circles_to_bboxes(circles) -> list:
    return [(int(x) - int(r), int(y) - int(r), int(x) + int(r), int(y) + int(r)) for x, y, r in circles]
```

**Comment by zeddo123** [comment]
Yes, I agree that the format that is currently returned is not optimal nor intuitive. We should change it to return the bounding boxes in `[xmin, ymin, xmax, ymax]`.

Concerning the overflow, could you provide some values to reproduce the warning?

**Comment by thamerkhamassi** [comment]
before fixing the overflow error and after
![proof](https://github.com/user-attachments/assets/91ed855a-b3ce-49ad-b1c1-fc29e0cb569b)
![circles_to_bboxes_4](https://github.com/user-attachments/assets/c496603f-8498-42c3-a905-f8cab6b7c8b9)
