### ISSUE TITLE
Handler and Output Step Selection Not Optimal in `output_on_image` Method

### ISSUE THREAD

**Issue by thamerkhamassi** [Octomiro/octopipes#20]
I encountered a problem when working with the `output_on_image` method in the octopipes workflow. Specifically, the current implementation uses the same index to select both the handler and the output, which limits flexibility and leads to issues in cases where the handler's step and the output step do not align perfectly. This method assumes that the step index in the workflow can be used to access both the handler and the output, but this is not always the case.

### Steps to Reproduce:
1. Create a workflow with multiple steps that use different handlers.
2. Try to output the result of an intermediate step where the handler and output index are different.
3. The `output_on_image` method fails due to the mismatch in expected output and handler processing.

### Current Behavior:
The `output_on_image` method currently relies on the same index to select both the handler and output. If different steps in the workflow produce outputs that require different handlers, this approach doesn't work optimally and can cause errors when the handler expects a different format than the provided output.

### Suggested Change:
Allow the user to specify the handler and output step explicitly, as demonstrated in the modified function below:

```python
def output_on_image(self, image, handler=-1, output=-1, save_to_file=True, path: str | None = None) -> None:
    import cv2

    handler = self.workflow.handlers[handler]
    output = self.outputs[output]
    
    if output is None:
        return

    img = image.copy()
    img: Any = handler.output_on_image(img, output)

    if save_to_file:
        if path is not None:
            utils.write_image(img, path)
        else:
            raise ValueError('save_to_file set but path is None')

    else:
        cv2.imshow(self.workflow.name, img)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

**Comment by zeddo123** [comment]
Thanks for the issue!

@thamerkhamassi your suggestion might well work and fix the bug. However, from a user standpoint it's inconvenient to have to specify the handler and output separately. I suggest "signing" the `handlers` and `outputs` list so that when the `output` flag is selected it would point to the correct output and handler of that output.
